#!/bin/bash
#SBATCH --gres=gpu:1
#SBATCH --gres-flags=enforce-binding
#SBATCH --mem-per-cpu=8GB
#SBATCH -C gpu32
#SBATCH --time=7-00:00:00
#SBATCH --job-name="MODRES"
#SBATCH -o slurm-MODRES-%N.%j.out
#SBATCH --mail-user=kjain@knights.ucf.edu
#SBATCH --mail-type=END,FAIL
#SBATCH --requeue

python --version

echo CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES
nvidia-smi

VRAM=`nvidia-smi --query-gpu=memory.total --format=csv | head -2 | tail -1 | awk '{print $1}'`

echo $VRAM

CUDA_VISIBLE_DEVICES=0 python train.py --backbone resnet --lr 0.001 --nesterov --workers 4 --epochs 100 --crop-size 256 --batch-size 50 --gpu-ids 0 --checkname deeplab-resnet --eval-interval 1 --dataset coco

nvidia-smi
